language: python
python: 2.7
services: redis-server
env:
    - TOX_ENV=py27
    - TOX_ENV=flake8
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
matrix:
    - python: 3.5
      env:
        - TOX_ENV=py35
        - TOX_ENV=kinto-master
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
