on:
  push:
    branches:
      - master
  pull_request:

name: Lint
jobs:
  lint:
    name: Lint and check format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: pip install tox
      - run: tox -e flake8
